### ISSUE TITLE
[resource] - migration user

### ISSUE THREAD

**Issue by HugoVersiani** [Minnemi/minnemi-back#10]
![Image](https://user-images.githubusercontent.com/72815966/241772731-26a9fbdf-f848-4562-95e0-46d384962632.png)

## Modificação de migration

Já existe uma migration padrão "user" do Laravel, deve-se modificar com as especificações da imagem acima.

### Requisitos:

- Deve-se modificar com as especificações da imagem acima;
- Nenhum dos campos devem aceitar valores nulos (manter como "not null");
- O campo profile_picture deve ter um valor default chamado "default.png".

Obs: os campos "updated" e "created" vem da função Timestamps() do Laravel.

**Comment by arraysArrais** [comment]
PR aberto: https://github.com/Minnemi/minnemi-back/pull/17
