### ISSUE TITLE
[resource] - migration letter

### ISSUE THREAD

**Issue by HugoVersiani** [Minnemi/minnemi-back#11]
![Image](https://user-images.githubusercontent.com/72815966/241773389-bf99653d-4cab-44c9-937d-5a19800f8133.png)

## Modificação de migration

Já existe uma migration "letter", deve-se modificar com as especificações da imagem acima.

### Requisitos:

- Deve-se modificar com as especificações da imagem acima;
- Nenhum dos campos devem aceitar valores nulos (manter como "not null");
- Deve haver uma chave estrangeira (1:N) em user_id;
- Deve haver uma chave (1:1) em visibility_id;

- Obs: os campos "updated" e "created" vem da função Timestamps() do Laravel.

**Comment by arraysArrais** [comment]
PR aberto: https://github.com/Minnemi/minnemi-back/pull/15
