### ISSUE TITLE
[resource] - migration credential

### ISSUE THREAD

**Issue by HugoVersiani** [Minnemi/minnemi-back#12]
![Image](https://user-images.githubusercontent.com/72815966/241773520-d0baeea5-6e56-4873-833a-f256648699e7.png)

## Criação de migration

Deve-se criar uma migration com as especificações da imagem acima.

### Requisitos:

- Deve-se criar com as especificações da imagem acima;
- Nenhum dos campos devem aceitar valores nulos (manter como "not null");
- Deve haver uma chave (1:1) em user_id

Obs: os campos "updated" e "created" vem da função Timestamps() do Laravel.

**Comment by arraysArrais** [comment]
PR aberto: https://github.com/Minnemi/minnemi-back/pull/19
