### ISSUE TITLE
[resource] - migration draft

### ISSUE THREAD

**Issue by HugoVersiani** [Minnemi/minnemi-back#13]
![Image](https://user-images.githubusercontent.com/72815966/241774043-a79b685b-5f35-44e6-aa78-feab9946739d.png)

## Criação de migration

Deve-se criar uma migration com as especificações da imagem acima.

### Requisitos:

- Deve-se criar com as especificações da imagem acima;
- Nenhum dos campos devem aceitar valores nulos (manter como "not null");
- Deve haver uma chave (1:N) em user_id

Obs: os campos "updated" e "created" vem da função Timestamps() do Laravel.

**Comment by arraysArrais** [comment]
PR aberto: https://github.com/Minnemi/minnemi-back/pull/18
