### ISSUE TITLE
[resource] - migration visibility_type

### ISSUE THREAD

**Issue by HugoVersiani** [Minnemi/minnemi-back#14]
![Image](https://user-images.githubusercontent.com/72815966/241774146-da4d2de7-f792-4f76-90d6-bca2beb80e31.png)

## Criação de migration

Deve-se criar uma migration com as especificações da imagem acima.

### Requisitos:

- Deve-se criar com as especificações da imagem acima;
- Nenhum dos campos devem aceitar valores nulos (manter como "not null");
- Deve haver dois dados inseridos: 

```
id |  type
---------
1  |  public
2  |  private
```

Obs: os campos "updated" e "created" vem da função Timestamps() do Laravel.

**Comment by arraysArrais** [comment]
PR aberto: https://github.com/Minnemi/minnemi-back/pull/16
