### ISSUE TITLE
Migration de Carta

### ISSUE THREAD

**Issue by arraysArrais** [Minnemi/minnemi-back#7]
Criar uma migration para gerar uma tabela com o nome "Letter". Com os campos: 

-  id;
-  user_id;
-  letter_title;
-  letter
- visibility(publica ou não);
- date_to_send;
- datetime/timestamps.

A relação com a tabela usuários sera de 1:N. (Um usuário pode escrever N cartas)

**Comment by viniciuscosmome** [comment]
Merge realizado: #8
